language: c

sudo: required

services: docker

before_script: 
  - docker build \
      --build-arg VCS_REF=`git rev-parse --short HEAD` \
      --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
      --build-arg VERSION=`cat VERSION` \
      -t axeclbr/git .

script: bats --tap test
