#!/bin/bash

if [ -z "$GIT_EMAIL" ] || [ -z "$GIT_NAME" ]; then
	echo "Please provide environment variable \"GIT_NAME\" and \"GIT_EMAIL\"."
fi;

docker run -it \
	-e "GIT_COMMITTER_NAME=$GIT_NAME" \
	-e "GIT_AUTHOR_NAME=$GIT_NAME" \
	-e "GIT_COMMITTER_EMAIL=$GIT_EMAIL" \
	-e "GIT_AUTHOR_EMAIL=$GIT_EMAIL" \
	-v $(pwd):/root/workspace \
	axeclbr/git "$@"